M48
; DRILL file {KiCad 9.0.6} date 2025-11-11T11:50:56+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-11T11:50:56+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X32.5Y-47.5
X32.5Y-72.5
X67.5Y-47.5
X67.5Y-72.5
M30
